[package]
name = "elk"
version = "0.1.0"
authors = ["esposm03 <36164633+esposm03@users.noreply.github.com>"]
edition = "2018"

[dependencies]
delf = { path = "../delf" }
mmap = "0.1.1"
region = "2.2.0"
custom_debug_derive = "0.5"
thiserror = "1.0.24"
enumflags2 = "0.7.1"
